spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: tester
      password: haul2

  thymeleaf:  
    prefix: classpath:templates/
    suffix: .html
   

  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp

      
  devtools:
    livereload:
      enabled: true
      
  jpa:
    database: mysql
    open-in-view: false
      
server:
  port: 8443
  
  ssl:
    key-store: C:\Users\sungw\springAnimalCommunitySSL\test.jks
    key-store-password: 123456
    key-store-type: jks
    key-alias: test
    
mybatis:
  mapper-locations: classpath:mapper/**/*.xml 
  
logging:
  level:
    '[org.springframework.web]': debug