spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&?characterEncoding=UTF-8"
      username: tester
      password: haul2

  thymeleaf:  
    prefix: classpath:templates/
    suffix: .html
   
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  mvc:
    converters:
      preferred-json-mapper: gson

  devtools:
    livereload:
      enabled: true
      
  jpa:
    database: mysql
    open-in-view: false
      
server:
  port: 8443
  
  ssl:
    key-store: C:\Users\sungw\springAnimalCommunitySSL\test.jks
    key-store-password: 123456
    key-store-type: jks
    key-alias: test
    
mybatis:
  mapper-locations: classpath:mapper/**/*.xml 
  
logging:
  level:
    '[org.springframework.web]': debug
    